//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "prebuild_replica")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub prebuild_id: Uuid,
    pub host_id: Uuid,
    pub user_id: Option<Uuid>,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prebuild::Entity",
        from = "Column::PrebuildId",
        to = "super::prebuild::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Prebuild,
    #[sea_orm(
        belongs_to = "super::workspace_host::Entity",
        from = "Column::HostId",
        to = "super::workspace_host::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WorkspaceHost,
}

impl Related<super::prebuild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prebuild.def()
    }
}

impl Related<super::workspace_host::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceHost.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
