//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "usage")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub start: DateTimeWithTimeZone,
    pub end: Option<DateTimeWithTimeZone>,
    pub resource_kind: String,
    pub resource_id: Uuid,
    pub resource_name: String,
    pub organization_id: Uuid,
    pub machine_type_id: Uuid,
    pub user_id: Option<Uuid>,
    pub duration: Option<i32>,
    pub cost_per_second: i32,
    pub total_cost: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::machine_type::Entity",
        from = "Column::MachineTypeId",
        to = "super::machine_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MachineType,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
}

impl Related<super::machine_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MachineType.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
