//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "workspace")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub organization_id: Uuid,
    pub user_id: Uuid,
    pub project_id: Option<Uuid>,
    pub prebuild_id: Option<Uuid>,
    pub name: String,
    pub service: Option<String>,
    pub status: String,
    pub repo_url: String,
    pub repo_name: String,
    pub branch: String,
    pub commit: String,
    pub host_id: Uuid,
    pub osuser: String,
    pub ssh_port: Option<i32>,
    pub ide_port: Option<i32>,
    pub ssh_private_key: String,
    pub ssh_public_key: String,
    pub env: Option<String>,
    pub cores: String,
    pub usage_id: Option<i32>,
    pub machine_type_id: Uuid,
    pub build_output: Option<String>,
    pub last_inactivity: Option<DateTimeWithTimeZone>,
    pub auto_start: bool,
    pub auto_stop: Option<i32>,
    pub is_compose: bool,
    pub compose_parent: Option<Uuid>,
    pub pinned: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::machine_type::Entity",
        from = "Column::MachineTypeId",
        to = "super::machine_type::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    MachineType,
    #[sea_orm(
        belongs_to = "super::workspace_host::Entity",
        from = "Column::HostId",
        to = "super::workspace_host::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    WorkspaceHost,
    #[sea_orm(has_many = "super::workspace_port::Entity")]
    WorkspacePort,
}

impl Related<super::machine_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MachineType.def()
    }
}

impl Related<super::workspace_host::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceHost.def()
    }
}

impl Related<super::workspace_port::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspacePort.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
