//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kube_cluster")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub organization_id: Uuid,
    pub created_by: Uuid,
    pub name: String,
    pub cluster_version: Option<String>,
    pub status: Option<String>,
    pub region: Option<String>,
    pub last_reported_at: Option<DateTimeWithTimeZone>,
    pub can_deploy: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::kube_app_catalog::Entity")]
    KubeAppCatalog,
    #[sea_orm(has_many = "super::kube_environment::Entity")]
    KubeEnvironment,
}

impl Related<super::kube_app_catalog::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeAppCatalog.def()
    }
}

impl Related<super::kube_environment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
