//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kube_environment_workload")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub environment_id: Uuid,
    pub name: String,
    pub namespace: String,
    pub kind: String,
    pub containers: Json,
    pub ports: Json,
    pub catalog_sync_version: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kube_environment::Entity",
        from = "Column::EnvironmentId",
        to = "super::kube_environment::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeEnvironment,
}

impl Related<super::kube_environment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
