//! `SeaORM` Entity, @generated by devbox_session plan implementation

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kube_devbox_service_intercept")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub session_id: Uuid,
    pub user_id: Uuid,
    pub environment_id: Uuid,
    pub workload_id: Uuid,
    pub service_id: Option<Uuid>,
    pub target_port: i32,
    pub local_port: i32,
    pub intercept_mode: String,
    pub config_map_name: String,
    pub routing_key: String,
    pub sidecar_auth_token_hash: String,
    pub tunnel_id: Uuid,
    pub original_proxy_config: String,
    pub created_at: DateTimeWithTimeZone,
    pub restored_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kube_devbox_session::Entity",
        from = "Column::SessionId",
        to = "super::kube_devbox_session::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeDevboxSession,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::kube_environment::Entity",
        from = "Column::EnvironmentId",
        to = "super::kube_environment::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeEnvironment,
    #[sea_orm(
        belongs_to = "super::kube_environment_workload::Entity",
        from = "Column::WorkloadId",
        to = "super::kube_environment_workload::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeEnvironmentWorkload,
    #[sea_orm(
        belongs_to = "super::kube_environment_service::Entity",
        from = "Column::ServiceId",
        to = "super::kube_environment_service::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeEnvironmentService,
}

impl Related<super::kube_devbox_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeDevboxSession.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::kube_environment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironment.def()
    }
}

impl Related<super::kube_environment_workload::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironmentWorkload.def()
    }
}

impl Related<super::kube_environment_service::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironmentService.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
