//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kube_environment_preview_url")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub environment_id: Uuid,
    pub service_id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub port: i32,
    pub port_name: Option<String>,
    pub protocol: String,
    pub access_level: String,
    pub created_by: Uuid,
    pub last_accessed_at: Option<DateTimeWithTimeZone>,
    pub metadata: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kube_environment::Entity",
        from = "Column::EnvironmentId",
        to = "super::kube_environment::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeEnvironment,
    #[sea_orm(
        belongs_to = "super::kube_environment_service::Entity",
        from = "Column::ServiceId",
        to = "super::kube_environment_service::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeEnvironmentService,
}

impl Related<super::kube_environment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironment.def()
    }
}

impl Related<super::kube_environment_service::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironmentService.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
