//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kube_environment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub organization_id: Uuid,
    pub user_id: Uuid,
    pub app_catalog_id: Uuid,
    pub cluster_id: Uuid,
    pub name: String,
    pub namespace: String,
    pub status: Option<String>,
    pub is_shared: bool,
    pub base_environment_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kube_app_catalog::Entity",
        from = "Column::AppCatalogId",
        to = "super::kube_app_catalog::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeAppCatalog,
    #[sea_orm(
        belongs_to = "super::kube_cluster::Entity",
        from = "Column::ClusterId",
        to = "super::kube_cluster::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeCluster,
    #[sea_orm(has_many = "super::kube_environment_preview_url::Entity")]
    KubeEnvironmentPreviewUrl,
    #[sea_orm(has_many = "super::kube_environment_service::Entity")]
    KubeEnvironmentService,
    #[sea_orm(has_many = "super::kube_environment_workload::Entity")]
    KubeEnvironmentWorkload,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::BaseEnvironmentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    BaseEnvironment,
}

impl Related<super::kube_app_catalog::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeAppCatalog.def()
    }
}

impl Related<super::kube_cluster::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeCluster.def()
    }
}

impl Related<super::kube_environment_preview_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironmentPreviewUrl.def()
    }
}

impl Related<super::kube_environment_service::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironmentService.def()
    }
}

impl Related<super::kube_environment_workload::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironmentWorkload.def()
    }
}

impl Related<Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BaseEnvironment.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
