//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14 (manually extended)

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kube_cluster_service")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub cluster_id: Uuid,
    pub namespace: String,
    pub name: String,
    pub resource_version: String,
    #[sea_orm(column_type = "Text")]
    pub service_yaml: String,
    pub selector: Json,
    pub ports: Json,
    pub service_type: Option<String>,
    pub cluster_ip: Option<String>,
    pub last_observed_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kube_cluster::Entity",
        from = "Column::ClusterId",
        to = "super::kube_cluster::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    KubeCluster,
}

impl Related<super::kube_cluster::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeCluster.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
