//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kube_environment_service")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub environment_id: Uuid,
    pub name: String,
    pub namespace: String,
    #[sea_orm(column_type = "Text")]
    pub yaml: String,
    pub ports: Json,
    pub selector: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::kube_environment::Entity",
        from = "Column::EnvironmentId",
        to = "super::kube_environment::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    KubeEnvironment,
    #[sea_orm(has_many = "super::kube_environment_preview_url::Entity")]
    KubeEnvironmentPreviewUrl,
}

impl Related<super::kube_environment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironment.def()
    }
}

impl Related<super::kube_environment_preview_url::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KubeEnvironmentPreviewUrl.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
