//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub provider: String,
    pub avatar_url: Option<String>,
    pub email: Option<String>,
    pub name: Option<String>,
    pub osuser: String,
    pub current_organization: Uuid,
    pub cluster_admin: bool,
    pub disabled: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::audit_log::Entity")]
    AuditLog,
    #[sea_orm(has_many = "super::usage::Entity")]
    Usage,
}

impl Related<super::audit_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuditLog.def()
    }
}

impl Related<super::usage::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Usage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
